CREATE DATABASE RTO;
USE RTO;
CREATE TABLE RTO.LLR_INFO (LLR_ID INT PRIMARY KEY,COLUMN_2 VARCHAR(50),COLUMN_3 VARCHAR(50),COLUMN_4 VARCHAR(50),COLUMN_5 VARCHAR(50),COLUMN_6 VARCHAR(50),COLUMN_7 VARCHAR(50),COLUMN_8 VARCHAR(50),COLUMN_9 VARCHAR(50),COLUMN_10 VARCHAR(50));
CREATE TABLE RTO.LLR_TEST_INFO (LLR_ID INT,TEST_ID INT PRIMARY KEY,COLUMN_3 VARCHAR(50),COLUMN_4 VARCHAR(50),COLUMN_5 VARCHAR(50),COLUMN_6 VARCHAR(50),COLUMN_7 VARCHAR(50),COLUMN_8 VARCHAR(50),COLUMN_9 VARCHAR(50),COLUMN_10 VARCHAR(50),FOREIGN KEY (LLR_ID) REFERENCES RTO.LLR_INFO(LLR_ID));
CREATE TABLE RTO.DRIVING_LICENCE_INFO (DL_ID INT PRIMARY KEY,TEST_ID INT,LLR_ID INT,COLUMN_4 VARCHAR(50),COLUMN_5 VARCHAR(50),COLUMN_6 VARCHAR(50),COLUMN_7 VARCHAR(50),COLUMN_8 VARCHAR(50),COLUMN_9 VARCHAR(50),COLUMN_10 VARCHAR(50),FOREIGN KEY (TEST_ID) REFERENCES RTO.LLR_TEST_INFO(TEST_ID),FOREIGN KEY (LLR_ID) REFERENCES RTO.LLR_INFO(LLR_ID));
CREATE TABLE RTO.DRIVING_LICENSE_TEST_INFO (DL_ID INT,COLUMN_2 VARCHAR(50),COLUMN_3 VARCHAR(50),COLUMN_4 VARCHAR(50),COLUMN_5 VARCHAR(50),COLUMN_6 VARCHAR(50),COLUMN_7 VARCHAR(50),COLUMN_8 VARCHAR(50),COLUMN_9 VARCHAR(50),COLUMN_10 VARCHAR(50),FOREIGN KEY (DL_ID) REFERENCES RTO.DRIVING_LICENCE_INFO(DL_ID));
INSERT INTO RTO.LLR_INFO (LLR_ID, COLUMN_2, COLUMN_3, COLUMN_4, COLUMN_5, COLUMN_6, COLUMN_7, COLUMN_8, COLUMN_9, COLUMN_10)
VALUES
(1, 'Value2', 'Value3', 'Value4', 'Value5', 'Value6', 'Value7', 'Value8', 'Value9', 'Value10'),
(2, 'Value2', 'Value3', 'Value4', 'Value5', 'Value6', 'Value7', 'Value8', 'Value9', 'Value10');
INSERT INTO RTO.LLR_TEST_INFO (LLR_ID, TEST_ID, COLUMN_3, COLUMN_4, COLUMN_5, COLUMN_6, COLUMN_7, COLUMN_8, COLUMN_9, COLUMN_10)
VALUES
(1, 101, 'Value3', 'Value4', 'Value5', 'Value6', 'Value7', 'Value8', 'Value9', 'Value10'),
(2, 102, 'Value3', 'Value4', 'Value5', 'Value6', 'Value7', 'Value8', 'Value9', 'Value10');
INSERT INTO RTO.DRIVING_LICENCE_INFO (DL_ID, TEST_ID, LLR_ID, COLUMN_4, COLUMN_5, COLUMN_6, COLUMN_7, COLUMN_8, COLUMN_9, COLUMN_10)
VALUES
(1, 101, 1, 'Value4', 'Value5', 'Value6', 'Value7', 'Value8', 'Value9', 'Value10'),
(2, 102, 2, 'Value4', 'Value5', 'Value6', 'Value7', 'Value8', 'Value9', 'Value10');
INSERT INTO RTO.DRIVING_LICENSE_TEST_INFO (DL_ID, COLUMN_2, COLUMN_3, COLUMN_4, COLUMN_5, COLUMN_6, COLUMN_7, COLUMN_8, COLUMN_9, COLUMN_10)
VALUES
(1, 'Value2', 'Value3', 'Value4', 'Value5', 'Value6', 'Value7', 'Value8', 'Value9', 'Value10'),
(2, 'Value2', 'Value3', 'Value4', 'Value5', 'Value6', 'Value7', 'Value8', 'Value9', 'Value10');
INSERT INTO RTO.LLR_INFO (LLR_ID, COLUMN_2, COLUMN_3, COLUMN_4, COLUMN_5, COLUMN_6, COLUMN_7, COLUMN_8, COLUMN_9, COLUMN_10)
VALUES (1, 'NewValue2', 'NewValue3', 'NewValue4', 'NewValue5', 'NewValue6', 'NewValue7', 'NewValue8', 'NewValue9', 'NewValue10')
ON DUPLICATE KEY UPDATE COLUMN_2 = VALUES(COLUMN_2),COLUMN_3 = VALUES(COLUMN_3),COLUMN_4 = VALUES(COLUMN_4),COLUMN_5 = VALUES(COLUMN_5),COLUMN_6 = VALUES(COLUMN_6),COLUMN_7 = VALUES(COLUMN_7),COLUMN_8 = VALUES(COLUMN_8),COLUMN_9 = VALUES(COLUMN_9),COLUMN_10 = VALUES(COLUMN_10);

REPLACE INTO LLR_INFO (LLR_ID, COLUMN_2, COLUMN_3, COLUMN_4, COLUMN_5, COLUMN_6, COLUMN_7, COLUMN_8, COLUMN_9, COLUMN_10)
VALUES (1, 'ReplacedValue2', 'ReplacedValue3', 'ReplacedValue4', 'ReplacedValue5', 'ReplacedValue6', 'ReplacedValue7', 'ReplacedValue8', 'ReplacedValue9', 'ReplacedValue10');